CC = g++ 
CFLAGS = -o -Wall
DEPS = stack.hpp

stack: clean
	$(CC) stack.cpp -o stack.x -Wall 

array: clean
	$(CC) arraylist.cxx -o arraylist.x -Wall
	./arraylist.x



clean:
	rm -f *.o *.c *.x *.gz *.txt 