

Drag:
	javac DragImage.java && java DragImage

Points:
	javac Points.java && java Points

Simple:
	javac SimpleGui.java && java SimpleGUI 

Start:
	javac Start && java Start


Turtle:
	javac Turtle.java && java Turtle

contains:
	javac contains.java && java contains